### ISSUE TITLE
V5 Checklist

### ISSUE THREAD

**Issue by Wykks** [Wykks/ngx-mapbox-gl#149]
Configurable NgZone behavior (and run mapbox-gl Inside NgZone by default, instead of outside). Some design inspiration here: https://github.com/ngxs/store/tree/master/packages/store/src/execution

ETA: Aborted. Looks like only very few peoples have issues with mapbox-gl running outside NgZone by default. And in this case, it's just a call to ngZon.run().

- [x] Source dynamic input issue https://github.com/Wykks/ngx-mapbox-gl/issues/139
More info: https://github.com/Wykks/ngx-mapbox-gl/issues/139#issuecomment-500066768

ETA : Done for image source in v3.3.0. Reported for the next major version
**PR welcome**

- [x] Move doc to repositoy (create a doc directory and create markdown file there)
-> add a way to select major version to access old doc in showcase app (using git branch)

ETA: Will do, required for v5.0 (at least the doc inside the repo, showcase can be done later).

- [x] Add prettier (https://github.com/Wykks/ngx-mapbox-gl/pull/210)

ETA: Will do, required for v5.0

- [x] Rename conflicting output name (https://github.com/Wykks/ngx-mapbox-gl/issues/107)
-> Activate this http://codelyzer.com/rules/no-output-native/

ETA: **PR welcome**, required for v4.0

- [x] Angular 8 support (rebuild everything on top of it; check if v3.x is okay with Angular 8).
- [x] mapbox-gl 1.0 support
- [x] Rework of mgl-marker-cluster (mapbox-gl expose supercluster functions natively since https://github.com/mapbox/mapbox-gl-js/pull/6829). Will be available in v3.x https://github.com/Wykks/ngx-mapbox-gl/pull/151

**Comment by BernhardRode** [comment]
I've just updated my app to:

`   
   "@angular/animations": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    [...]
    "mapbox-gl": "^1.0.0",
    [...]
    "ngx-mapbox-gl": "^3.1.0",
    [...]
`

Everything worked like a charm for me. But i'm not using all of ngx-mapbox-gl features. But I think 2 and 3 should not give many problems =)

**Comment by Wykks** [comment]
Some ETA (because I probably won't make it in short term..):
Worked on new component api "markers-of-clusters" (using external geojson source). Looks good :)

Nothing else for now. It's "hard" for me to work on this: I'm not using mapbox-gl anymore (don't have use case atm), and I have other stuff to do in my spare time. 

PR are welcome by the way :smile:

**Comment by SamuelDev** [comment]
We are using Angular 6 and Mapbox 1.0.0.  Will V4 work with Angular 6 still, or will it only support 8?

**Comment by Wykks** [comment]
Hi!

v4 will target Angular 8 (and 9).

What kind a feature do you want ?
New marker cluster component will available in v3 (https://github.com/Wykks/ngx-mapbox-gl/pull/151).

I hesitate to add support of mapbox-gl 1.0 (new features in particular), because there are some breaking changes, so in theory I can only add it in v4.
But these breaking change probably wont affect most of users so... Dunno...

**Comment by dmytro-gokun** [comment]
@Wykks Please let me know what issue(s) you'd like to have a PR for. I'd like help speeding up V4 arrival, but do not like stepping on someone else's foot by working on the same issue in parallel :)

**Comment by Wykks** [comment]
Post updated :)
I'll keep this updated if I start working on "PR welcome" tasks. 
Thanks for your help!

**Comment by itslenny** [comment]
Running ngx-mapbox-gl on angular 9 I get the following error. Figure this might help y'all on your path to angular 9 support. In the meantime, anyone have any ideas for a work around?

```
Fetch API cannot load height: 100%; mapbox://styles/lennyjoe/cjo0b1o4ca7zw2srv8lfuwpyn. URL scheme must be "http" or "https" for CORS request.
```

**Comment by itslenny** [comment]
Running ngx-mapbox-gl on angular 9 I get the following error. Figure this might help y'all on your path to angular 9 support. In the meantime, anyone have any ideas for a work around?

```
Fetch API cannot load height: 100%; mapbox://styles/lennyjoe/zzzzzzzzzz. URL scheme must be "http" or "https" for CORS request.
```
<img width="940" alt="Screen Shot 2020-02-09 at 4 37 37 PM" src="https://user-images.githubusercontent.com/5210230/74113708-d1f73380-4b5a-11ea-8288-4f79473d919d.png">
